#!/usr/bin/env bash
# Interactive first-run setup for the Dealroom next-gen API hackathon skill.
# Prompts for credentials, writes them to .env in the current directory,
# fetches an access token, and makes a test call.

set -euo pipefail

AUTH_URL="https://accounts.beta.dealroom.co/oauth/token"
API_BASE="https://api-next.beta.dealroom.co"
AUDIENCE="https://api-next.beta.dealroom.co"
ENV_FILE="${ENV_FILE:-.env}"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
red() { printf "\033[31m%s\033[0m\n" "$1"; }
green() { printf "\033[32m%s\033[0m\n" "$1"; }

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    red "Missing dependency: $1"
    echo "Install it and re-run."
    exit 1
  fi
}

require_cmd curl
require_cmd jq

bold "Dealroom next-gen API — local setup"
echo "This will write credentials to: $(pwd)/$ENV_FILE"
echo

if [[ -f "$ENV_FILE" ]]; then
  read -r -p "$ENV_FILE already exists. Overwrite? [y/N] " ans
  if [[ "${ans:-N}" != "y" && "${ans:-N}" != "Y" ]]; then
    echo "Aborted."
    exit 0
  fi
fi

read -r -p "client_id (from https://app-next.beta.dealroom.co/settings/api): " CLIENT_ID
read -r -s -p "client_secret (shown only once when you created the key): " CLIENT_SECRET
echo
read -r -p "User-Agent (e.g. 'HackathonApp/0.1 (you@example.com)'): " USER_AGENT

if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" || -z "$USER_AGENT" ]]; then
  red "All three values are required."
  exit 1
fi

bold "Requesting access token..."
TOKEN_RESPONSE=$(curl -s -X POST "$AUTH_URL" \
  -H "Content-Type: application/json" \
  -d "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"audience\":\"$AUDIENCE\",\"grant_type\":\"client_credentials\"}")

ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token // empty')
EXPIRES_IN=$(echo "$TOKEN_RESPONSE" | jq -r '.expires_in // empty')

if [[ -z "$ACCESS_TOKEN" ]]; then
  red "Token exchange failed. Response was:"
  echo "$TOKEN_RESPONSE" | jq .
  echo
  echo "Common causes:"
  echo "  - Wrong client_id or client_secret (re-check Settings > API)"
  echo "  - Key was revoked or expired"
  echo "  - You generated a Browser-app key instead of Programmatic (M2M)"
  exit 1
fi

green "Got access token (expires in ${EXPIRES_IN}s)."

cat > "$ENV_FILE" <<EOF
# Dealroom next-gen API credentials — generated by next-gen-api-hackathon skill
# DO NOT COMMIT. Add this file to .gitignore.

DEALROOM_API_BASE="$API_BASE"
DEALROOM_AUTH_URL="$AUTH_URL"
DEALROOM_AUDIENCE="$AUDIENCE"

DEALROOM_CLIENT_ID="$CLIENT_ID"
DEALROOM_CLIENT_SECRET="$CLIENT_SECRET"
DEALROOM_USER_AGENT="$USER_AGENT"

# Refreshed by scripts/refresh-token.sh — valid for ~24h after issue.
DEALROOM_ACCESS_TOKEN="$ACCESS_TOKEN"
EOF

chmod 600 "$ENV_FILE"
green "Wrote $ENV_FILE (mode 600)."

bold "Making a test call to /api/entities..."
TEST=$(curl -s -o /tmp/dealroom-test.json -w "%{http_code}" \
  "$API_BASE/api/entities?limit=1" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "User-Agent: $USER_AGENT" \
  -H "X-Client-Id: $CLIENT_ID")

if [[ "$TEST" == "200" ]]; then
  NAME=$(jq -r '.data[0].name // "(no results)"' /tmp/dealroom-test.json)
  green "Success — sample entity: $NAME"
  echo
  echo "Next steps:"
  echo "  1. Add .env to .gitignore"
  echo "  2. Source .env in your shell:  source $ENV_FILE"
  echo "  3. Run requests with the headers shown in SKILL.md"
else
  red "Test call returned HTTP $TEST."
  echo "Response:"
  jq . /tmp/dealroom-test.json 2>/dev/null || cat /tmp/dealroom-test.json
  echo
  echo "Credentials are saved to $ENV_FILE but the API rejected the request."
  echo "Check references/troubleshooting.md in the skill folder."
  exit 1
fi
